DROP TABLE Addresses CASCADE CONSTRAINTS;
DROP TABLE Countries CASCADE CONSTRAINTS;
DROP TABLE CustomerOrders CASCADE CONSTRAINTS;
DROP TABLE Dishes CASCADE CONSTRAINTS;
DROP TABLE DishIngredients CASCADE CONSTRAINTS;
DROP TABLE Ingredients CASCADE CONSTRAINTS;
DROP TABLE Menus CASCADE CONSTRAINTS;
DROP TABLE OrderDishes CASCADE CONSTRAINTS;
DROP TABLE OrderIngredients CASCADE CONSTRAINTS;
DROP TABLE Reservations CASCADE CONSTRAINTS;
DROP TABLE RestaurantIngredients CASCADE CONSTRAINTS;
DROP TABLE Restaurants CASCADE CONSTRAINTS;
DROP TABLE Roles CASCADE CONSTRAINTS;
DROP TABLE SupplierIngredients CASCADE CONSTRAINTS;
DROP TABLE SupplierOrders CASCADE CONSTRAINTS;
DROP TABLE Suppliers CASCADE CONSTRAINTS;
DROP TABLE Tables CASCADE CONSTRAINTS;
DROP TABLE UserRoles CASCADE CONSTRAINTS;
DROP TABLE Users CASCADE CONSTRAINTS;
DROP TABLE RoleClaims CASCADE CONSTRAINTS;
DROP TABLE UserClaims CASCADE CONSTRAINTS;
DROP TABLE UserLogins CASCADE CONSTRAINTS;
DROP TABLE UserTokens CASCADE CONSTRAINTS;


--------------------------------------------------------
--  DDL for Table Addresses
--------------------------------------------------------

  CREATE TABLE Addresses 
   (	Id NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	CountryId NUMBER(10,0), 
	PostalCode NVARCHAR2(2000), 
	City NVARCHAR2(2000), 
	Street NVARCHAR2(2000), 
	StreetNumber NVARCHAR2(2000)
   );
--------------------------------------------------------
--  DDL for Table Countries
--------------------------------------------------------

  CREATE TABLE Countries 
   (	Id NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	Name NVARCHAR2(2000), 
	CountryCode NVARCHAR2(2000)
   );
--------------------------------------------------------
--  DDL for Table CustomerOrders
--------------------------------------------------------

  CREATE TABLE CustomerOrders 
   (	Id NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	Takeout NUMBER(1,0), 
	OrderTime TIMESTAMP (7), 
	TotalPrice NUMBER(10,0), 
	AssignedEmployeeId NUMBER(10,0), 
	RestaurantId NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table Dishes
--------------------------------------------------------

  CREATE TABLE Dishes 
   (	Id NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	Name NVARCHAR2(2000), 
	Price NUMBER(10,0), 
	MenuId NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table DishIngredients
--------------------------------------------------------

  CREATE TABLE DishIngredients 
   (	DishId NUMBER(10,0), 
	IngredientId NUMBER(10,0), 
	Amount BINARY_FLOAT
   );

--------------------------------------------------------
--  DDL for Table Ingredients
--------------------------------------------------------

  CREATE TABLE Ingredients 
   (	Id NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	Name NVARCHAR2(2000), 
	IsPricePerKilogram NUMBER(1,0), 
	Price NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table Menus
--------------------------------------------------------

  CREATE TABLE Menus 
   (	Id NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
   );
--------------------------------------------------------
--  DDL for Table OrderDishes
--------------------------------------------------------

  CREATE TABLE OrderDishes 
   (	OrderId NUMBER(10,0), 
	DishId NUMBER(10,0), 
	Count NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table OrderIngredients
--------------------------------------------------------

  CREATE TABLE OrderIngredients 
   (	SupplierOrderId NUMBER(10,0), 
	IngredientId NUMBER(10,0), 
	Amount BINARY_FLOAT DEFAULT TO_BINARY_FLOAT(0)
   );
--------------------------------------------------------
--  DDL for Table Reservations
--------------------------------------------------------

  CREATE TABLE Reservations 
   (	Id NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	TableId NUMBER(10,0), 
	StartTime TIMESTAMP (7), 
	EndTime TIMESTAMP (7), 
	Name NVARCHAR2(2000)
   );
--------------------------------------------------------
--  DDL for Table RestaurantIngredients
--------------------------------------------------------

  CREATE TABLE RestaurantIngredients 
   (	RestaurantId NUMBER(10,0), 
	IngredientId NUMBER(10,0), 
	Amount BINARY_FLOAT
   );
--------------------------------------------------------
--  DDL for Table Restaurants
--------------------------------------------------------

  CREATE TABLE Restaurants 
   (	Id NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	Name NVARCHAR2(2000), 
	AddressId NUMBER(10,0), 
	MenuId NUMBER(10,0), 
	OwnerId NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table RoleClaims
--------------------------------------------------------

  CREATE TABLE RoleClaims 
   (	Id NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	RoleId NUMBER(10,0), 
	ClaimType NVARCHAR2(2000), 
	ClaimValue NVARCHAR2(2000)
   );
--------------------------------------------------------
--  DDL for Table Roles
--------------------------------------------------------

  CREATE TABLE Roles 
   (	Id NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	Name NVARCHAR2(256), 
	NormalizedName NVARCHAR2(256), 
	ConcurrencyStamp NVARCHAR2(2000)
   );
--------------------------------------------------------
--  DDL for Table SupplierIngredients
--------------------------------------------------------

  CREATE TABLE SupplierIngredients 
   (	SupplierId NUMBER(10,0), 
	IngredientId NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table SupplierOrders
--------------------------------------------------------

    CREATE TABLE SupplierOrders
(	
    Id NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
    "Date" TIMESTAMP (7), 
    SupplierId NUMBER(10,0), 
    RestaurantId NUMBER(10,0)
);
--------------------------------------------------------
--  DDL for Table Suppliers
--------------------------------------------------------

  CREATE TABLE Suppliers 
   (	Id NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	Name NVARCHAR2(2000), 
	BankInformation NVARCHAR2(2000), 
	AddressId NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table Tables
--------------------------------------------------------

  CREATE TABLE Tables 
   (	Id NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	SeatCount NUMBER(10,0), 
	Name NVARCHAR2(2000), 
	RestaurantId NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table UserClaims
--------------------------------------------------------

  CREATE TABLE UserClaims 
   (	Id NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	UserId NUMBER(10,0), 
	ClaimType NVARCHAR2(2000), 
	ClaimValue NVARCHAR2(2000)
   ) ;
--------------------------------------------------------
--  DDL for Table UserLogins
--------------------------------------------------------

  CREATE TABLE UserLogins 
   (	UserId NUMBER(10,0), 
	LoginProvider NVARCHAR2(2000), 
	ProviderKey NVARCHAR2(2000), 
	ProviderDisplayName NVARCHAR2(2000)
   );
--------------------------------------------------------
--  DDL for Table UserRoles
--------------------------------------------------------

  CREATE TABLE UserRoles 
   (	UserId NUMBER(10,0), 
	RoleId NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table Users
--------------------------------------------------------

  CREATE TABLE Users 
   (	Id NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	Name NVARCHAR2(2000), 
	Surname NVARCHAR2(2000), 
	Salary NUMBER(10,0), 
	BirthDate TIMESTAMP (7), 
	PESEL NVARCHAR2(2000), 
	RestaurantId NUMBER(10,0), 
	UserName NVARCHAR2(256), 
	NormalizedUserName NVARCHAR2(256), 
	Email NVARCHAR2(256), 
	NormalizedEmail NVARCHAR2(256), 
	EmailConfirmed NUMBER(1,0), 
	PasswordHash NVARCHAR2(2000), 
	SecurityStamp NVARCHAR2(2000), 
	ConcurrencyStamp NVARCHAR2(2000), 
	PhoneNumber NVARCHAR2(2000), 
	PhoneNumberConfirmed NUMBER(1,0), 
	TwoFactorEnabled NUMBER(1,0), 
	LockoutEnd TIMESTAMP (7) WITH TIME ZONE, 
	LockoutEnabled NUMBER(1,0), 
	AccessFailedCount NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table UserTokens
--------------------------------------------------------

  CREATE TABLE UserTokens 
   (	UserId NUMBER(10,0), 
	LoginProvider NVARCHAR2(2000), 
	Name NVARCHAR2(2000), 
	Value NVARCHAR2(2000)
   );


Insert into Addresses values ('3','1','00-020','mario land','toad st','9/2');
Insert into Addresses values ('21','1','00-000','mario land','castle street','1');
Insert into Addresses values ('41','1','00-000','mario land','test street','8');
Insert into Addresses values ('42','1','11111','GREGLAND','GREG STREET','99');
Insert into Addresses values ('61','1','11-444','AAA','Dane','244');
Insert into Addresses values ('43','1','34-900','Nowhere','ACME st.','1');

Insert into Countries values ('1','mushroom kingdom','MK');

Insert into CustomerOrders values ('1','1',to_timestamp('22/01/09 23:04:45,113000000','RR/MM/DD HH24:MI:SSXFF'),'1000','3','1');
Insert into CustomerOrders values ('21','0',to_timestamp('22/01/11 23:03:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'9000','26','1');
Insert into CustomerOrders values ('22','0',to_timestamp('22/01/11 23:04:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'9000','26','1');
Insert into CustomerOrders values ('23','1',to_timestamp('22/01/11 23:04:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'9000','26','1');
Insert into CustomerOrders values ('24','0',to_timestamp('22/01/11 23:05:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'9000','26','1');
Insert into CustomerOrders values ('25','0',to_timestamp('22/01/11 23:05:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'0','26','1');
Insert into CustomerOrders values ('26','0',to_timestamp('22/01/11 23:07:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'9000','1','1');
Insert into CustomerOrders values ('27','0',to_timestamp('22/01/11 23:07:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'9000','1','1');
Insert into CustomerOrders values ('28','1',to_timestamp('22/01/11 23:07:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'19000','1','1');
Insert into CustomerOrders values ('29','1',to_timestamp('22/01/11 23:09:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'9000','1','1');
Insert into CustomerOrders values ('30','0',to_timestamp('22/01/11 23:09:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'19000','1','1');
Insert into CustomerOrders values ('31','0',to_timestamp('22/01/11 23:10:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'18000','26','1');
Insert into CustomerOrders values ('32','1',to_timestamp('22/01/11 23:10:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'9000','26','1');
Insert into CustomerOrders values ('33','0',to_timestamp('22/01/12 10:43:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'9000','3','1');
Insert into CustomerOrders values ('34','0',to_timestamp('22/01/12 10:43:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'18000','3','1');
Insert into CustomerOrders values ('41','0',to_timestamp('22/01/12 22:45:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'19000','1','1');
Insert into CustomerOrders values ('42','1',to_timestamp('22/01/12 22:45:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'9000','1','1');
Insert into CustomerOrders values ('43','0',to_timestamp('22/01/12 22:48:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'9000','26','1');
Insert into CustomerOrders values ('44','0',to_timestamp('22/01/12 23:05:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'9000','1','1');
Insert into CustomerOrders values ('45','0',to_timestamp('22/01/13 13:12:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'9000','3','1');
Insert into CustomerOrders values ('46','0',to_timestamp('22/01/13 20:24:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'1000','26','1');
Insert into CustomerOrders values ('61','0',to_timestamp('22/01/14 13:05:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'9000','3','1');
Insert into CustomerOrders values ('62','0',to_timestamp('22/01/14 18:55:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'18000','1','1');
Insert into CustomerOrders values ('63','0',to_timestamp('22/01/15 20:12:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'9000','26','1');
Insert into CustomerOrders values ('64','1',to_timestamp('22/01/15 20:12:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'17000','26','1');
Insert into CustomerOrders values ('65','0',to_timestamp('22/01/15 21:05:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'4000','26','1');
Insert into CustomerOrders values ('81','0',to_timestamp('22/01/17 16:50:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'11500','1','1');

Insert into Dishes values ('2','mushroom stew','1000','1');
Insert into Dishes values ('3','mushroom stew 2: mario special','9000','1');
Insert into Dishes values ('4','mushroom stew 3: luigi special','9000','1');
Insert into Dishes values ('38','chlebek','1000','1');
Insert into Dishes values ('39','kompocik','2000','1');
Insert into Dishes values ('24','zupka','500','1');
Insert into Dishes values ('28','pierogi','4000','1');

Insert into DishIngredients values ('4','2','5,0');
Insert into DishIngredients values ('38','42','10000,0');
Insert into DishIngredients values ('39','2','10000,0');
Insert into DishIngredients values ('38','2','100,0');
Insert into DishIngredients values ('39','44','100,0');

Insert into Ingredients values ('3','green mushroom','0','2000');
Insert into Ingredients values ('2','red mushroom','1','300');
Insert into Ingredients values ('21','test','0','1000');
Insert into Ingredients values ('22','abcd','1','1000');
Insert into Ingredients values ('23','abcd','1','1000');
Insert into Ingredients values ('24','test2','0','4000');
Insert into Ingredients values ('25','test2','0','4000');
Insert into Ingredients values ('26','1234','0','1000');
Insert into Ingredients values ('27','1234','0','1000');
Insert into Ingredients values ('41','�mietana','1','1000');
Insert into Ingredients values ('42','�mietana','1','1000');
Insert into Ingredients values ('43','bu�ki','0','4000');
Insert into Ingredients values ('44','bu�ki','0','4000');
Insert into Ingredients values ('45','woda','1','1000');
Insert into Ingredients values ('46','woda','1','1000');
Insert into Ingredients values ('47','mandarynki','0','10000');
Insert into Ingredients values ('48','mandarynki','0','10000');
Insert into Ingredients values ('61','test5','0','100000');
Insert into Ingredients values ('62','test5','0','100000');
Insert into Ingredients values ('63','test5','0','-1500');
Insert into Ingredients values ('64','test5','0','-1500');

Insert into Menus values ('1');

Insert into OrderDishes values ('1','4','5');
Insert into OrderDishes values ('21','4','1');
Insert into OrderDishes values ('22','3','1');
Insert into OrderDishes values ('23','4','1');
Insert into OrderDishes values ('24','4','1');
Insert into OrderDishes values ('26','4','1');
Insert into OrderDishes values ('27','3','1');
Insert into OrderDishes values ('28','2','1');
Insert into OrderDishes values ('28','3','1');
Insert into OrderDishes values ('28','4','1');
Insert into OrderDishes values ('29','4','1');
Insert into OrderDishes values ('30','2','1');
Insert into OrderDishes values ('30','3','1');
Insert into OrderDishes values ('30','4','1');
Insert into OrderDishes values ('31','3','1');
Insert into OrderDishes values ('31','4','1');
Insert into OrderDishes values ('32','3','1');
Insert into OrderDishes values ('33','4','1');
Insert into OrderDishes values ('34','3','1');
Insert into OrderDishes values ('34','4','1');
Insert into OrderDishes values ('41','2','1');
Insert into OrderDishes values ('41','3','1');
Insert into OrderDishes values ('41','4','1');
Insert into OrderDishes values ('42','3','1');
Insert into OrderDishes values ('43','4','1');
Insert into OrderDishes values ('44','3','1');
Insert into OrderDishes values ('45','4','1');
Insert into OrderDishes values ('46','2','1');
Insert into OrderDishes values ('61','4','1');
Insert into OrderDishes values ('62','3','1');
Insert into OrderDishes values ('62','4','1');
Insert into OrderDishes values ('65','28','1');
Insert into OrderDishes values ('81','4','1');
Insert into OrderDishes values ('81','24','1');
Insert into OrderDishes values ('81','39','1');

Insert into OrderIngredients values ('5','3','5000,0');
Insert into OrderIngredients values ('22','3','50,0');
Insert into OrderIngredients values ('22','24','600,0');
Insert into OrderIngredients values ('22','25','1,5');
Insert into OrderIngredients values ('22','26','0,0');
Insert into OrderIngredients values ('23','24','36,0');
Insert into OrderIngredients values ('23','25','8888,0');
Insert into OrderIngredients values ('24','3','111,0');
Insert into OrderIngredients values ('24','44','11111,0');
Insert into OrderIngredients values ('29','23','15,0');
Insert into OrderIngredients values ('29','46','15,0');
Insert into OrderIngredients values ('29','48','40,0');
Insert into OrderIngredients values ('30','23','12,0');
Insert into OrderIngredients values ('30','46','1666,0');

Insert into Reservations values ('1','1',to_timestamp('22/01/08 18:29:55,517000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/08 20:29:55,517000000','RR/MM/DD HH24:MI:SSXFF'),'wario');
Insert into Reservations values ('2','1',to_timestamp('22/01/09 18:29:55,517000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/09 20:29:55,517000000','RR/MM/DD HH24:MI:SSXFF'),'waluigi');
Insert into Reservations values ('23','2',to_timestamp('22/01/09 01:04:00,338000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/09 12:15:00,338000000','RR/MM/DD HH24:MI:SSXFF'),'boo');
Insert into Reservations values ('24','3',to_timestamp('22/01/09 01:04:00,000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/09 20:15:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'aaaaa');
Insert into Reservations values ('25','2',to_timestamp('22/01/10 01:04:00,000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/10 20:15:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'aaaaa');
Insert into Reservations values ('26','1',to_timestamp('22/01/10 01:04:00,000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/10 20:15:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'aaaaa');
Insert into Reservations values ('27','3',to_timestamp('22/01/10 01:04:00,000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/10 20:15:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'aaaaa');
Insert into Reservations values ('31','1',to_timestamp('22/01/09 01:02:00,000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/09 01:56:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'htr');
Insert into Reservations values ('29','2',to_timestamp('22/01/09 15:37:00,000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/09 21:37:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'kowalski');
Insert into Reservations values ('30','2',to_timestamp('22/01/11 15:37:00,000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/11 21:37:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'aaaaaa');
Insert into Reservations values ('41','3',to_timestamp('22/01/16 12:14:00,000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/16 14:16:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'eht');
Insert into Reservations values ('42','2',to_timestamp('22/01/12 01:14:00,000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/12 01:36:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'hubsor');
Insert into Reservations values ('43','1',to_timestamp('22/01/12 15:16:00,000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/12 15:18:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'rht');
Insert into Reservations values ('44','3',to_timestamp('22/01/12 15:16:00,000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/12 15:18:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'rht');
Insert into Reservations values ('45','2',to_timestamp('22/01/12 12:16:00,000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/12 14:00:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'hubert');
Insert into Reservations values ('46','3',to_timestamp('22/01/12 12:16:00,000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/12 14:00:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'hubert');
Insert into Reservations values ('61','3',to_timestamp('22/01/11 12:30:00,000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/11 18:00:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'jeremy');
Insert into Reservations values ('62','1',to_timestamp('22/01/11 14:16:00,000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/11 16:12:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'abcd');
Insert into Reservations values ('81','3',to_timestamp('22/01/15 12:44:00,000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/15 15:41:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'24');
Insert into Reservations values ('82','2',to_timestamp('22/01/15 12:15:00,000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/15 20:16:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'aaaaaaaa');
Insert into Reservations values ('83','2',to_timestamp('22/01/13 15:16:00,000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/13 20:12:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'aaaa');
Insert into Reservations values ('101','3',to_timestamp('22/01/14 20:22:00,000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/14 22:20:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'trollge');
Insert into Reservations values ('102','1',to_timestamp('22/01/14 12:33:00,000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/14 23:59:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'kreg');
Insert into Reservations values ('103','3',to_timestamp('22/01/14 23:12:00,000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/14 23:55:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'adgsdgas');
Insert into Reservations values ('104','1',to_timestamp('22/01/15 12:16:00,000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/15 14:18:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'hsoroka');
Insert into Reservations values ('105','3',to_timestamp('22/01/22 12:16:00,000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/22 14:16:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'hsoroka');
Insert into Reservations values ('121','1',to_timestamp('22/01/22 14:16:00,000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/22 18:16:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'hsoroka');

Insert into RestaurantIngredients values ('1','2','-105,0');
Insert into RestaurantIngredients values ('1','23','27,0');
Insert into RestaurantIngredients values ('1','3','5161,0');
Insert into RestaurantIngredients values ('1','25','8889,5');
Insert into RestaurantIngredients values ('1','27','0,0');
Insert into RestaurantIngredients values ('1','24','636,0');
Insert into RestaurantIngredients values ('1','26','0,0');
Insert into RestaurantIngredients values ('1','42','0,0');
Insert into RestaurantIngredients values ('1','44','11011,0');
Insert into RestaurantIngredients values ('1','46','1681,0');
Insert into RestaurantIngredients values ('1','48','40,0');
Insert into RestaurantIngredients values ('1','62','0,0');
Insert into RestaurantIngredients values ('1','64','0,0');

Insert into Restaurants values ('1','mario''s diner','3','1','1');

Insert into Roles values ('1','Owner','OWNER','f5c3c5e3-c3a2-4352-aab9-66a932f5a974');
Insert into Roles values ('2','Manager','MANAGER','69929fd0-d8ab-4ca4-8406-0dc07fa7f68b');
Insert into Roles values ('3','Employee','EMPLOYEE','83aebd41-1606-499b-9a8e-13bf945cd3f6');
Insert into Roles values ('4','Admin','ADMIN','02739071-15a3-4560-a8b6-c8d3bd93cab6');

Insert into SupplierIngredients values ('1','3');
Insert into SupplierIngredients values ('1','24');
Insert into SupplierIngredients values ('1','25');
Insert into SupplierIngredients values ('1','26');
Insert into SupplierIngredients values ('1','44');
Insert into SupplierIngredients values ('1','48');
Insert into SupplierIngredients values ('21','25');
Insert into SupplierIngredients values ('21','27');
Insert into SupplierIngredients values ('22','23');
Insert into SupplierIngredients values ('22','42');
Insert into SupplierIngredients values ('22','46');
Insert into SupplierIngredients values ('22','48');

Insert into SupplierOrders values ('22',to_timestamp('22/01/15 19:05:37,985661900','RR/MM/DD HH24:MI:SSXFF'),'1','1');
Insert into SupplierOrders values ('23',to_timestamp('22/01/15 19:07:01,909285400','RR/MM/DD HH24:MI:SSXFF'),'1','1');
Insert into SupplierOrders values ('24',to_timestamp('22/01/16 17:25:51,630362300','RR/MM/DD HH24:MI:SSXFF'),'1','1');
Insert into SupplierOrders values ('25',to_timestamp('22/01/17 01:28:35,027880500','RR/MM/DD HH24:MI:SSXFF'),'1','1');
Insert into SupplierOrders values ('5',to_timestamp('22/01/09 22:24:55,720505000','RR/MM/DD HH24:MI:SSXFF'),'1','1');
Insert into SupplierOrders values ('21',to_timestamp('22/01/15 18:38:53,099812900','RR/MM/DD HH24:MI:SSXFF'),'1','1');
Insert into SupplierOrders values ('26',to_timestamp('22/01/17 15:19:27,974264300','RR/MM/DD HH24:MI:SSXFF'),'23','1');
Insert into SupplierOrders values ('27',to_timestamp('22/01/17 15:19:29,524117900','RR/MM/DD HH24:MI:SSXFF'),'23','1');
Insert into SupplierOrders values ('28',to_timestamp('22/01/17 15:19:45,973548100','RR/MM/DD HH24:MI:SSXFF'),'22','1');
Insert into SupplierOrders values ('29',to_timestamp('22/01/17 15:19:53,757117000','RR/MM/DD HH24:MI:SSXFF'),'22','1');
Insert into SupplierOrders values ('30',to_timestamp('22/01/17 15:54:49,992930400','RR/MM/DD HH24:MI:SSXFF'),'22','1');

Insert into Suppliers values ('1','Royal Mushroom Farm','22222','21');
Insert into Suppliers values ('21','Test Labs. Inc','4220002020200202002','41');
Insert into Suppliers values ('22','Greg''s apple stash','1234575434','42');
Insert into Suppliers values ('23','ACME Inc.','1212121212121121212121112121','43');
Insert into Suppliers values ('41','The Mandarynki','1247433','61');

Insert into Tables values ('1','1','the "Mario 64"','1');
Insert into Tables values ('2','8','the "Mario Kart"','1');
Insert into Tables values ('3','4','the "New Super Mario Bros. U Deluxe"','1');

Insert into UserRoles values ('1','1');
Insert into UserRoles values ('2','4');
Insert into UserRoles values ('3','3');
Insert into UserRoles values ('24','3');
Insert into UserRoles values ('26','3');
Insert into UserRoles values ('101','3');
Insert into UserRoles values ('121','2');
Insert into UserRoles values ('141','3');

Insert into Users values ('1','mario','kart','0',to_timestamp('22/01/07 17:59:22,884000000','RR/MM/DD HH24:MI:SSXFF'),'00000000000',null,'mario','MARIO',null,null,'0','AQAAAAEAACcQAAAAEPS3wD+t4y9h74Hp2Ps+8Vv7rhfDkOTSfX0PIUmZZJvKUva0yRlWFVEEVW1wvnNwIw==','SWN6B4AAZU4PTOMG5CIDHLA5JEC4TNAG','cfd74c01-5eb1-4b47-bc58-b6e1c6200d16',null,'0','0',null,'0','0');
Insert into Users values ('2','admin','admin','0',to_timestamp('22/01/07 17:59:22,884000000','RR/MM/DD HH24:MI:SSXFF'),'00000000000',null,'admin','ADMIN',null,null,'0','AQAAAAEAACcQAAAAEDUwLmWuK/JigjwBtE1g51OVmwVuMKJoXAeIZoPYZXempNxNlOk3wtAcGicAPSVbAA==','LRK6RYIJSKBYE2VR5JNWHLYBKCRLPWGQ','5178b1b1-3102-439a-ae6e-c6b2f2271901',null,'0','0',null,'0','0');
Insert into Users values ('3','luigi','mario','10000000',to_timestamp('80/01/14 13:50:33,706000000','RR/MM/DD HH24:MI:SSXFF'),'00000000000000000000','1','luigi','LUIGI',null,null,'0','AQAAAAEAACcQAAAAEEvg8fNDSNT+bu7h47l3c+SxTyc3r+fRWOB+1g8k/K8vMVjNEGMIDIl7Magt2pqi3g==','VTIKAMJ3KUYTOWLRPA7GCBR5LAQX5XQF','be9df0fe-57d4-414e-97bb-670af6c6cd73',null,'0','0',null,'0','0');
Insert into Users values ('141','a','b','400000',to_timestamp('22/01/17 15:27:00,000000000','RR/MM/DD HH24:MI:SSXFF'),null,'1','Test','TEST',null,null,'0','AQAAAAEAACcQAAAAEIWE41dlSxawr+c+DjkonkdDlaZRtpNQDVWLZY0RCQXMrSzFyYCDZ+88U3gQsTsEVQ==','75SLS3USGTWCX7NZT4PKC36I37SQANH6','de7869ac-7a65-4e3b-8fbd-82f2f0830a1f',null,'0','0',null,'0','0');
Insert into Users values ('24','hub','sor','400000',to_timestamp('01/06/20 00:00:00,000000000','RR/MM/DD HH24:MI:SSXFF'),'123456789','1','hubsor','HUBSOR',null,null,'0','AQAAAAEAACcQAAAAEHdlfkGb/NN1XAaICxg2ilmoaUmAfubyS0EXeDStkKcEcPON7tXui3pGIb4rhxuQXA==','ODOWW7A3KIBW3Y3LYHAJKHXG377MCHCJ','e3351f52-2389-4c46-9c3a-0b80e66427ca',null,'0','0',null,'0','0');
Insert into Users values ('26','ab','cd','400000',to_timestamp('01/01/29 00:00:00,000000000','RR/MM/DD HH24:MI:SSXFF'),null,'1','abcd','ABCD',null,null,'0','AQAAAAEAACcQAAAAEOtUCRuMI0UOMgoVfsq4gzZQaIAFMu1WZLb7QMbYdBmRm5sDXc6cAS/jj3uYjWW4HQ==','PKXC6BUZ2AQY4SHBCNUBWL3CMGM27YYD','ee730760-8024-4d62-b662-ebe5ee0d05b4',null,'0','0',null,'0','0');
Insert into Users values ('121','marcin','najman','600000',to_timestamp('00/01/01 00:00:00,000000000','RR/MM/DD HH24:MI:SSXFF'),null,'1','najman','NAJMAN',null,null,'0','AQAAAAEAACcQAAAAEBoTh82682xDP40jP9ZLWrO/rwdOKFuRT2q8MeqXRbpGAg+FJ+zvxi5f6IRQZ2yqnw==','FHMMDHAB3QIHZKXMNXRMOVB6ZMSL2SAM','ca4a32a3-e02e-4b23-bac5-932dc4197e67',null,'0','0',null,'0','0');
Insert into Users values ('101','Peach','Princess','600000',to_timestamp('85/09/13 00:00:00,000000000','RR/MM/DD HH24:MI:SSXFF'),null,'1','another_castle','ANOTHER_CASTLE',null,null,'0','AQAAAAEAACcQAAAAEP3Df4YoSeIxQnhbjohPppLmK3NbxKbkHv1KyIfBfJSJvDEhN/+F8Fy+OSXPeO/e8g==','YQSRWMVSBUSBPWVJOU3AZNKNZV35LYS7','475c3bfb-08a1-44e3-b8c3-85d592843f06',null,'0','0',null,'0','0');



--------------------------------------------------------
--  DDL for Index PK_Addresses
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_Addresses ON Addresses (Id);
--------------------------------------------------------
--  DDL for Index PK_Countries
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_Countries ON Countries (Id);
--------------------------------------------------------
--  DDL for Index PK_CustomerOrders
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_CustomerOrders ON CustomerOrders (Id);
--------------------------------------------------------
--  DDL for Index PK_DishIngredients
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_DishIngredients ON DishIngredients (DishId, IngredientId);
--------------------------------------------------------
--  DDL for Index PK_Dishes
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_Dishes ON Dishes (Id);
--------------------------------------------------------
--  DDL for Index PK_Ingredients
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_Ingredients ON Ingredients (Id);
--------------------------------------------------------
--  DDL for Index PK_Menus
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_Menus ON Menus (Id);
--------------------------------------------------------
--  DDL for Index PK_OrderDishes
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_OrderDishes ON OrderDishes (OrderId, DishId);
--------------------------------------------------------
--  DDL for Index PK_OrderIngredients
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_OrderIngredients ON OrderIngredients (SupplierOrderId, IngredientId);
--------------------------------------------------------
--  DDL for Index PK_Reservations
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_Reservations ON Reservations (Id);
--------------------------------------------------------
--  DDL for Index PK_RestaurantIngredients
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_RestaurantIngredients ON RestaurantIngredients (RestaurantId, IngredientId);
--------------------------------------------------------
--  DDL for Index PK_Restaurants
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_Restaurants ON Restaurants (Id);
--------------------------------------------------------
--  DDL for Index PK_RoleClaims
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_RoleClaims ON RoleClaims (Id);
--------------------------------------------------------
--  DDL for Index PK_Roles
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_Roles ON Roles (Id);
--------------------------------------------------------
--  DDL for Index PK_SupplierIngredients
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_SupplierIngredients ON SupplierIngredients (SupplierId, IngredientId);
--------------------------------------------------------
--  DDL for Index PK_SupplierOrders
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_SupplierOrders ON SupplierOrders (Id);
--------------------------------------------------------
--  DDL for Index PK_Suppliers
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_Suppliers ON Suppliers (Id);
--------------------------------------------------------
--  DDL for Index PK_Tables
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_Tables ON Tables (Id);
--------------------------------------------------------
--  DDL for Index PK_UserClaims
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_UserClaims ON UserClaims (Id);
--------------------------------------------------------
--  DDL for Index PK_UserLogins
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_UserLogins ON UserLogins (UserId);
--------------------------------------------------------
--  DDL for Index PK_UserRoles
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_UserRoles ON UserRoles (UserId, RoleId);
--------------------------------------------------------
--  DDL for Index PK_UserTokens
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_UserTokens ON UserTokens (UserId);
--------------------------------------------------------
--  DDL for Index PK_Users
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_Users ON Users (Id);
--------------------------------------------------------
--  DDL for Index IX_UserClaims_UserId
--------------------------------------------------------

  CREATE INDEX IX_UserClaims_UserId ON UserClaims (UserId);
--------------------------------------------------------
--  DDL for Index IX_DishIngredients_IngredientId
--------------------------------------------------------

  CREATE INDEX IX_DishIngredients_IngredientId ON DishIngredients (IngredientId);
--------------------------------------------------------
--  DDL for Index IX_RestaurantIngredients_IngredientId
--------------------------------------------------------

  CREATE INDEX IX_RestaurantIngredients_IngredientId ON RestaurantIngredients (IngredientId);
--------------------------------------------------------
--  DDL for Index IX_Restaurants_AddressId
--------------------------------------------------------

  CREATE INDEX IX_Restaurants_AddressId ON Restaurants (AddressId);
--------------------------------------------------------
--  DDL for Index IX_Tables_RestaurantId
--------------------------------------------------------

  CREATE INDEX IX_Tables_RestaurantId ON Tables (RestaurantId);
--------------------------------------------------------
--  DDL for Index IX_Restaurants_MenuId
--------------------------------------------------------

  CREATE INDEX IX_Restaurants_MenuId ON Restaurants (MenuId);
--------------------------------------------------------
--  DDL for Index UserNameIndex
--------------------------------------------------------

  CREATE UNIQUE INDEX UserNameIndex ON Users (NormalizedUserName);
--------------------------------------------------------
--  DDL for Index IX_Addresses_CountryId
--------------------------------------------------------

  CREATE INDEX IX_Addresses_CountryId ON Addresses (CountryId);
--------------------------------------------------------
--  DDL for Index IX_RoleClaims_RoleId
--------------------------------------------------------

  CREATE INDEX IX_RoleClaims_RoleId ON RoleClaims (RoleId);
--------------------------------------------------------
--  DDL for Index EmailIndex
--------------------------------------------------------

  CREATE INDEX EmailIndex ON Users (NormalizedEmail);
--------------------------------------------------------
--  DDL for Index IX_OrderDishes_DishId
--------------------------------------------------------

  CREATE INDEX IX_OrderDishes_DishId ON OrderDishes (DishId);
--------------------------------------------------------
--  DDL for Index IX_SupplierIngredients_IngredientId
--------------------------------------------------------

  CREATE INDEX IX_SupplierIngredients_IngredientId ON SupplierIngredients (IngredientId);
--------------------------------------------------------
--  DDL for Index IX_Reservations_TableId
--------------------------------------------------------

  CREATE INDEX IX_Reservations_TableId ON Reservations (TableId);
--------------------------------------------------------
--  DDL for Index IX_Dishes_MenuId
--------------------------------------------------------

  CREATE INDEX IX_Dishes_MenuId ON Dishes (MenuId);
--------------------------------------------------------
--  DDL for Index RoleNameIndex
--------------------------------------------------------

  CREATE UNIQUE INDEX RoleNameIndex ON Roles (NormalizedName);
--------------------------------------------------------
--  DDL for Index IX_OrderIngredients_IngredientId
--------------------------------------------------------

  CREATE INDEX IX_OrderIngredients_IngredientId ON OrderIngredients (IngredientId);
--------------------------------------------------------
--  DDL for Index IX_Restaurants_OwnerId
--------------------------------------------------------

  CREATE INDEX IX_Restaurants_OwnerId ON Restaurants (OwnerId);
--------------------------------------------------------
--  DDL for Index IX_SupplierOrders_SupplierId
--------------------------------------------------------

  CREATE INDEX IX_SupplierOrders_SupplierId ON SupplierOrders (SupplierId);
--------------------------------------------------------
--  DDL for Index IX_CustomerOrders_RestaurantId
--------------------------------------------------------

  CREATE INDEX IX_CustomerOrders_RestaurantId ON CustomerOrders (RestaurantId);
--------------------------------------------------------
--  DDL for Index IX_SupplierOrders_RestaurantId
--------------------------------------------------------

  CREATE INDEX IX_SupplierOrders_RestaurantId ON SupplierOrders (RestaurantId);
--------------------------------------------------------
--  DDL for Index IX_CustomerOrders_AssignedEmployeeId
--------------------------------------------------------

  CREATE INDEX IX_CustomerOrders_AssignedEmployeeId ON CustomerOrders (AssignedEmployeeId);
--------------------------------------------------------
--  DDL for Index IX_Suppliers_AddressId
--------------------------------------------------------

  CREATE INDEX IX_Suppliers_AddressId ON Suppliers (AddressId);
--------------------------------------------------------
--  DDL for Index IX_Users_RestaurantId
--------------------------------------------------------

  CREATE INDEX IX_Users_RestaurantId ON Users (RestaurantId);
--------------------------------------------------------
--  DDL for Index IX_UserRoles_RoleId
--------------------------------------------------------

  CREATE INDEX IX_UserRoles_RoleId ON UserRoles (RoleId);
--------------------------------------------------------
--  Constraints for Table RoleClaims
--------------------------------------------------------

  ALTER TABLE RoleClaims ADD CONSTRAINT PK_RoleClaims PRIMARY KEY (Id);
  ALTER TABLE RoleClaims MODIFY (RoleId NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table UserClaims
--------------------------------------------------------

  ALTER TABLE UserClaims ADD CONSTRAINT PK_UserClaims PRIMARY KEY (Id);
  ALTER TABLE UserClaims MODIFY (UserId NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DishIngredients
--------------------------------------------------------

  ALTER TABLE DishIngredients ADD CONSTRAINT PK_DishIngredients PRIMARY KEY (DishId, IngredientId);
  ALTER TABLE DishIngredients MODIFY (DishId NOT NULL ENABLE);
  ALTER TABLE DishIngredients MODIFY (IngredientId NOT NULL ENABLE);
  ALTER TABLE DishIngredients MODIFY (Amount NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table Ingredients
--------------------------------------------------------

  ALTER TABLE Ingredients ADD CONSTRAINT PK_Ingredients PRIMARY KEY (Id);
  ALTER TABLE Ingredients MODIFY (IsPricePerKilogram NOT NULL ENABLE);
  ALTER TABLE Ingredients MODIFY (Price NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table Dishes
--------------------------------------------------------

  ALTER TABLE Dishes ADD CONSTRAINT PK_Dishes PRIMARY KEY (Id);
  ALTER TABLE Dishes MODIFY (Price NOT NULL ENABLE);
  ALTER TABLE Dishes MODIFY (MenuId NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table UserRoles
--------------------------------------------------------

  ALTER TABLE UserRoles ADD CONSTRAINT PK_UserRoles PRIMARY KEY (UserId, RoleId);
  ALTER TABLE UserRoles MODIFY (UserId NOT NULL ENABLE);
  ALTER TABLE UserRoles MODIFY (RoleId NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table UserLogins
--------------------------------------------------------

  ALTER TABLE UserLogins ADD CONSTRAINT PK_UserLogins PRIMARY KEY (UserId);
  ALTER TABLE UserLogins MODIFY (UserId NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table Menus
--------------------------------------------------------

  ALTER TABLE Menus ADD CONSTRAINT PK_Menus PRIMARY KEY (Id);
--------------------------------------------------------
--  Constraints for Table Addresses
--------------------------------------------------------

  ALTER TABLE Addresses ADD CONSTRAINT PK_Addresses PRIMARY KEY (Id);
  ALTER TABLE Addresses MODIFY (CountryId NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table Users
--------------------------------------------------------

  ALTER TABLE Users ADD CONSTRAINT PK_Users PRIMARY KEY (Id);
  ALTER TABLE Users MODIFY (Salary NOT NULL ENABLE);
  ALTER TABLE Users MODIFY (BirthDate NOT NULL ENABLE);
  ALTER TABLE Users MODIFY (EmailConfirmed NOT NULL ENABLE);
  ALTER TABLE Users MODIFY (PhoneNumberConfirmed NOT NULL ENABLE);
  ALTER TABLE Users MODIFY (TwoFactorEnabled NOT NULL ENABLE);
  ALTER TABLE Users MODIFY (LockoutEnabled NOT NULL ENABLE);
  ALTER TABLE Users MODIFY (AccessFailedCount NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table Restaurants
--------------------------------------------------------

  ALTER TABLE Restaurants ADD CONSTRAINT PK_Restaurants PRIMARY KEY (Id);
  ALTER TABLE Restaurants MODIFY (AddressId NOT NULL ENABLE);
  ALTER TABLE Restaurants MODIFY (MenuId NOT NULL ENABLE);
  ALTER TABLE Restaurants MODIFY (OwnerId NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table Countries
--------------------------------------------------------

  ALTER TABLE Countries ADD CONSTRAINT PK_Countries PRIMARY KEY (Id);
--------------------------------------------------------
--  Constraints for Table RestaurantIngredients
--------------------------------------------------------

  ALTER TABLE RestaurantIngredients ADD CONSTRAINT PK_RestaurantIngredients PRIMARY KEY (RestaurantId, IngredientId);
  ALTER TABLE RestaurantIngredients MODIFY (RestaurantId NOT NULL ENABLE);
  ALTER TABLE RestaurantIngredients MODIFY (IngredientId NOT NULL ENABLE);
  ALTER TABLE RestaurantIngredients MODIFY (Amount NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table Tables
--------------------------------------------------------

  ALTER TABLE Tables ADD CONSTRAINT PK_Tables PRIMARY KEY (Id);
  ALTER TABLE Tables MODIFY (SeatCount NOT NULL ENABLE);
  ALTER TABLE Tables MODIFY (RestaurantId NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table Roles
--------------------------------------------------------

  ALTER TABLE Roles ADD CONSTRAINT PK_Roles PRIMARY KEY (Id);
--------------------------------------------------------
--  Constraints for Table UserTokens
--------------------------------------------------------

  ALTER TABLE UserTokens ADD CONSTRAINT PK_UserTokens PRIMARY KEY (UserId);
  ALTER TABLE UserTokens MODIFY (UserId NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OrderIngredients
--------------------------------------------------------

  ALTER TABLE OrderIngredients ADD CONSTRAINT PK_OrderIngredients PRIMARY KEY (SupplierOrderId, IngredientId);
  ALTER TABLE OrderIngredients MODIFY (SupplierOrderId NOT NULL ENABLE);
  ALTER TABLE OrderIngredients MODIFY (IngredientId NOT NULL ENABLE);
  ALTER TABLE OrderIngredients MODIFY (Amount NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SupplierOrders
--------------------------------------------------------

  ALTER TABLE SupplierOrders ADD CONSTRAINT PK_SupplierOrders PRIMARY KEY (Id);
  ALTER TABLE SupplierOrders MODIFY ("Date" NOT NULL ENABLE);
  ALTER TABLE SupplierOrders MODIFY (SupplierId NOT NULL ENABLE);
  ALTER TABLE SupplierOrders MODIFY (RestaurantId NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table Reservations
--------------------------------------------------------

  ALTER TABLE Reservations ADD CONSTRAINT PK_Reservations PRIMARY KEY (Id);
  ALTER TABLE Reservations MODIFY (TableId NOT NULL ENABLE);
  ALTER TABLE Reservations MODIFY (StartTime NOT NULL ENABLE);
  ALTER TABLE Reservations MODIFY (EndTime NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OrderDishes
--------------------------------------------------------

  ALTER TABLE OrderDishes ADD CONSTRAINT PK_OrderDishes PRIMARY KEY (OrderId, DishId);
  ALTER TABLE OrderDishes MODIFY (OrderId NOT NULL ENABLE);
  ALTER TABLE OrderDishes MODIFY (DishId NOT NULL ENABLE);
  ALTER TABLE OrderDishes MODIFY (Count NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SupplierIngredients
--------------------------------------------------------

  ALTER TABLE SupplierIngredients ADD CONSTRAINT PK_SupplierIngredients PRIMARY KEY (SupplierId, IngredientId);
  ALTER TABLE SupplierIngredients MODIFY (SupplierId NOT NULL ENABLE);
  ALTER TABLE SupplierIngredients MODIFY (IngredientId NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CustomerOrders
--------------------------------------------------------

  ALTER TABLE CustomerOrders ADD CONSTRAINT PK_CustomerOrders PRIMARY KEY (Id);
  ALTER TABLE CustomerOrders MODIFY (Takeout NOT NULL ENABLE);
  ALTER TABLE CustomerOrders MODIFY (OrderTime NOT NULL ENABLE);
  ALTER TABLE CustomerOrders MODIFY (TotalPrice NOT NULL ENABLE);
  ALTER TABLE CustomerOrders MODIFY (AssignedEmployeeId NOT NULL ENABLE);
  ALTER TABLE CustomerOrders MODIFY (RestaurantId NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table Suppliers
--------------------------------------------------------

  ALTER TABLE Suppliers ADD CONSTRAINT PK_Suppliers PRIMARY KEY (Id);
  ALTER TABLE Suppliers MODIFY (AddressId NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table Addresses
--------------------------------------------------------

  ALTER TABLE Addresses ADD CONSTRAINT FK_Addresses_Countries_CountryId FOREIGN KEY (CountryId)
	  REFERENCES Countries (Id) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CustomerOrders
--------------------------------------------------------

  ALTER TABLE CustomerOrders ADD CONSTRAINT FK_CustomerOrders_Restaurants_RestaurantId FOREIGN KEY (RestaurantId)
	  REFERENCES Restaurants (Id) ENABLE;
  ALTER TABLE CustomerOrders ADD CONSTRAINT FK_CustomerOrders_Users_AssignedEmployeeId FOREIGN KEY (AssignedEmployeeId)
	  REFERENCES Users (Id) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table Dishes
--------------------------------------------------------

  ALTER TABLE Dishes ADD CONSTRAINT FK_Dishes_Menus_MenuId FOREIGN KEY (MenuId)
	  REFERENCES Menus (Id) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DishIngredients
--------------------------------------------------------

  ALTER TABLE DishIngredients ADD CONSTRAINT FK_DishIngredients_Dishes_DishId FOREIGN KEY (DishId)
	  REFERENCES Dishes (Id) ENABLE;
  ALTER TABLE DishIngredients ADD CONSTRAINT FK_DishIngredients_Ingredients_IngredientId FOREIGN KEY (IngredientId)
	  REFERENCES Ingredients (Id) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OrderDishes
--------------------------------------------------------

  ALTER TABLE OrderDishes ADD CONSTRAINT FK_OrderDishes_CustomerOrders_OrderId FOREIGN KEY (OrderId)
	  REFERENCES CustomerOrders (Id) ENABLE;
  ALTER TABLE OrderDishes ADD CONSTRAINT FK_OrderDishes_Dishes_DishId FOREIGN KEY (DishId)
	  REFERENCES Dishes (Id) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OrderIngredients
--------------------------------------------------------

  ALTER TABLE OrderIngredients ADD CONSTRAINT FK_OrderIngredients_Ingredients_IngredientId FOREIGN KEY (IngredientId)
	  REFERENCES Ingredients (Id) ENABLE;
  ALTER TABLE OrderIngredients ADD CONSTRAINT FK_OrderIngredients_SupplierOrders_SupplierOrderId FOREIGN KEY (SupplierOrderId)
	  REFERENCES SupplierOrders (Id) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table Reservations
--------------------------------------------------------

  ALTER TABLE Reservations ADD CONSTRAINT FK_Reservations_Tables_TableId FOREIGN KEY (TableId)
	  REFERENCES Tables (Id) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RestaurantIngredients
--------------------------------------------------------

  ALTER TABLE RestaurantIngredients ADD CONSTRAINT FK_RestaurantIngredients_Ingredients_IngredientId FOREIGN KEY (IngredientId)
	  REFERENCES Ingredients (Id) ENABLE;
  ALTER TABLE RestaurantIngredients ADD CONSTRAINT FK_RestaurantIngredients_Restaurants_RestaurantId FOREIGN KEY (RestaurantId)
	  REFERENCES Restaurants (Id) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table Restaurants
--------------------------------------------------------

  ALTER TABLE Restaurants ADD CONSTRAINT FK_Restaurants_Addresses_AddressId FOREIGN KEY (AddressId)
	  REFERENCES Addresses (Id) ON DELETE CASCADE ENABLE;
  ALTER TABLE Restaurants ADD CONSTRAINT FK_Restaurants_Menus_MenuId FOREIGN KEY (MenuId)
	  REFERENCES Menus (Id) ON DELETE CASCADE ENABLE;
  ALTER TABLE Restaurants ADD CONSTRAINT FK_Restaurants_Users_OwnerId FOREIGN KEY (OwnerId)
	  REFERENCES Users (Id) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RoleClaims
--------------------------------------------------------

  ALTER TABLE RoleClaims ADD CONSTRAINT FK_RoleClaims_Roles_RoleId FOREIGN KEY (RoleId)
	  REFERENCES Roles (Id) ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SupplierIngredients
--------------------------------------------------------

  ALTER TABLE SupplierIngredients ADD CONSTRAINT FK_SupplierIngredients_Ingredients_IngredientId FOREIGN KEY (IngredientId)
	  REFERENCES Ingredients (Id) ENABLE;
  ALTER TABLE SupplierIngredients ADD CONSTRAINT FK_SupplierIngredients_Suppliers_SupplierId FOREIGN KEY (SupplierId)
	  REFERENCES Suppliers (Id) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SupplierOrders
--------------------------------------------------------

  ALTER TABLE SupplierOrders ADD CONSTRAINT FK_SupplierOrders_Restaurants_RestaurantId FOREIGN KEY (RestaurantId)
	  REFERENCES Restaurants (Id) ENABLE;
  ALTER TABLE SupplierOrders ADD CONSTRAINT FK_SupplierOrders_Suppliers_SupplierId FOREIGN KEY (SupplierId)
	  REFERENCES Suppliers (Id) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table Suppliers
--------------------------------------------------------

  ALTER TABLE Suppliers ADD CONSTRAINT FK_Suppliers_Addresses_AddressId FOREIGN KEY (AddressId)
	  REFERENCES Addresses (Id) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table Tables
--------------------------------------------------------

  ALTER TABLE Tables ADD CONSTRAINT FK_Tables_Restaurants_RestaurantId FOREIGN KEY (RestaurantId)
	  REFERENCES Restaurants (Id) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UserClaims
--------------------------------------------------------

  ALTER TABLE UserClaims ADD CONSTRAINT FK_UserClaims_Users_UserId FOREIGN KEY (UserId)
	  REFERENCES Users (Id) ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UserLogins
--------------------------------------------------------

  ALTER TABLE UserLogins ADD CONSTRAINT FK_UserLogins_Users_UserId FOREIGN KEY (UserId)
	  REFERENCES Users (Id) ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UserRoles
--------------------------------------------------------

  ALTER TABLE UserRoles ADD CONSTRAINT FK_UserRoles_Roles_RoleId FOREIGN KEY (RoleId)
	  REFERENCES Roles (Id) ON DELETE CASCADE ENABLE;
  ALTER TABLE UserRoles ADD CONSTRAINT FK_UserRoles_Users_UserId FOREIGN KEY (UserId)
	  REFERENCES Users (Id) ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table Users
--------------------------------------------------------

  ALTER TABLE Users ADD CONSTRAINT FK_Users_Restaurants_RestaurantId FOREIGN KEY (RestaurantId)
	  REFERENCES Restaurants (Id) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UserTokens
--------------------------------------------------------

  ALTER TABLE UserTokens ADD CONSTRAINT FK_UserTokens_Users_UserId FOREIGN KEY (UserId)
	  REFERENCES Users (Id) ON DELETE CASCADE ENABLE;


commit;